---
  - name: Launch Chameleon VMs
    hosts: MyLocalVMs
    remote_user: ubuntu
    gather_facts: yes
    become_user: no
    tasks:
      - name: launch VM2
        openstack.cloud.server:
          state: present
          cloud: CH-819381
          name: Team11_VM2
          image: CC-Ubuntu20.04
          availability_zone: nova
          key_name: CS4287_Group11_keypair
          timeout: 500
          flavor: m1.small
          security_groups:
            - ENABLE_HTTP_HTTPS
            - ENABLE_ICMP
            - ENABLE_K8s
            - ENABLE_KAFKA_COUCHDB
            - ENABLE_KAFKA_COUCH_SSH
            - ENABLE_SSH
            - ENABLE_WIREGUARD
            - ENABLE_ZMQ_APPS
          floating_ips: 
            - 129.114.27.56
          nics:
            - net-name: CH-819381-net
      - name: launch VM3
        openstack.cloud.server:
          state: present
          cloud: CH-819381
          name: Team11_VM3
          image: CC-Ubuntu20.04
          availability_zone: nova
          key_name: CS4287_Group11_keypair
          timeout: 500
          flavor: m1.small
          security_groups:
            - ENABLE_HTTP_HTTPS
            - ENABLE_ICMP
            - ENABLE_K8s
            - ENABLE_KAFKA_COUCHDB
            - ENABLE_KAFKA_COUCH_SSH
            - ENABLE_SSH
            - ENABLE_WIREGUARD
            - ENABLE_ZMQ_APPS
          floating_ips: 
            - 129.114.26.42
          nics:
            - net-name: CH-819381-net
...