---
- name: Configure ufw rules
  hosts: MyChameleonVMs
  remote_user: cc
  become: yes

  tasks:
    - name: Allow connections to port 9092
      ansible.builtin.shell: sudo ufw limit 9092/tcp
    - name: Allow connections to port 2181
      ansible.builtin.shell: sudo ufw limit 2181/tcp
    - name: Allow connections to port 6984
      ansible.builtin.shell: sudo ufw limit 6984/tcp
    - name: Allow connections to port 8080
      ansible.builtin.shell: sudo ufw limit 8080/tcp
    - name: Allow connections to port 2379-2380
      shell: sudo ufw limit 2379:2380/tcp
    - name: Allow connections to port 4040
      shell: sudo ufw limit 4040/tcp 
    - name: Allow connections to port 5000
      shell: sudo ufw limit 5000/tcp
    - name: Allow connections to port 6443
      shell: sudo ufw limit 6443/tcp 
    - name: Allow connections to port 7076-7079
      shell: sudo ufw limit 7076:7079/tcp
    - name: Allow connections to port 8001
      shell: sudo ufw limit 8001/tcp
    - name: Allow connections to port 8080-8081
      shell: sudo ufw limit 8080:8081/tcp
    - name: Allow connections to port 10250-10252
      shell: sudo ufw limit 10250:10252/tcp
    - name: Allow connections to port 30000-30010
      shell: sudo ufw limit 30000:30010/tcp
    - name: Allow connections to port 8285
      shell: sudo ufw limit 8285/tcp
    - name: Allow connections to port 8472
      shell: sudo ufw limit 8472/tcp
...