---
- hosts: MyChameleonVMs
  remote_user: cc
  gather_facts: yes
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
    - debug: {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
...